---
- name: Install epel
  yum:
    name:
      - epel-release
    state: latest

- name: Update system
  yum: name=* state=latest

- name: Install soft
  yum:
    name:
      - vmstat
      - iotop
      - atop
      - telnet
      - vim
    state: latest