---
- name: Install epel
  yum:
    name:
      - epel-release
    state: latest

- name: Update system
  yum: name=* state=latest

- name: Install Docker
  yum: name=docker state=latest

- name: Restart Docker
  service:
    name: docker
    enabled: true
    state: restarted

- name: Install Docker-Compose
  copy:
    src: docker-compose
    dest: /usr/local/bin/
    mode: 0755

- name: Create Docker dirs
  file:
    path: /etc/docker-manifests/elk
    state: directory
    mode: 0775

- name: Copy ELK to VM
  copy: src=docker-elk-master dest=/etc/docker-manifests/elk recursive=yes

- name: UP Docker-Compose
  command: docker-compose -f /etc/docker-manifests/elk/docker-elk-master/docker-compose.yml up -d