---
- name: Install epel
  yum:
    name:
      - epel-release
    state: latest

- name: Update system
  yum: name=* state=latest

- name: Install Docker
  yum: name=docker-ce state=latest

- name: Install Docker-Compose
  copy:
    src: docker-compose
    dest: usr/local/bin/
    mode: 0755

- name: Create Docker dirs
  file:
    path: /etc/docker-manifests/zabbix
    state: directory
    mode: 0775

- name: Copy Compose File to VM
  copy: src=dockercompose.yml dest=/etc/docker-manifests/zabbix

- name: UP Docker-Compose
  command: docker-compose -f /etc/docker-manifests/zabbix/docker-compose.yml up -d