---
- name: Install epel
  yum:
    name:
      - epel-release
    state: latest

- name: Update system
  yum: name=* state=latest

#- name: Adding Zabbix repository
#  command: rpm -ivh https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

- name: Frontend installation prerequisites
  command: yum-config-manager --enable rhel-7-server-optional-rpms

- name: Install Zabbix
  yum:
    name:
      - prepare-server-mysql
      - prepare-proxy-mysql
      - prepare-web-mysql
    state: latest
